Repository rtrdxSka/UIS, pull requests merged in 2023-12, with the labels that each got.

#34 Initial commit with updated architecture.
  UIS.FrontEnd/UIS/.editorconfig
  UIS.FrontEnd/UIS/.gitignore
  UIS.FrontEnd/UIS/.vscode/extensions.json
  UIS.FrontEnd/UIS/.vscode/launch.json
  UIS.FrontEnd/UIS/.vscode/tasks.json
  UIS.FrontEnd/UIS/README.md
  UIS.FrontEnd/UIS/angular.json
  UIS.FrontEnd/UIS/package-lock.json
  UIS.FrontEnd/UIS/package.json
  UIS.FrontEnd/UIS/src/app/app.component.css
  UIS.FrontEnd/UIS/src/app/app.component.html
  UIS.FrontEnd/UIS/src/app/app.component.spec.ts
  UIS.FrontEnd/UIS/src/app/app.component.ts
  UIS.FrontEnd/UIS/src/app/app.config.ts
  UIS.FrontEnd/UIS/src/app/app.routes.ts
  UIS.FrontEnd/UIS/src/app/components/moodle-sync/moodle-sync.component.css
  UIS.FrontEnd/UIS/src/app/components/moodle-sync/moodle-sync.component.html
  UIS.FrontEnd/UIS/src/app/components/moodle-sync/moodle-sync.component.ts
  UIS.FrontEnd/UIS/src/assets/.gitkeep
  UIS.FrontEnd/UIS/src/favicon.ico
  UIS.FrontEnd/UIS/src/index.html
  UIS.FrontEnd/UIS/src/main.ts
  UIS.FrontEnd/UIS/src/styles.css
  UIS.FrontEnd/UIS/tsconfig.app.json
  UIS.FrontEnd/UIS/tsconfig.json
  UIS.FrontEnd/UIS/tsconfig.spec.json
Labels: Task

#45 11 add an endpoint to handle moodle oauth callback
  .vscode/launch.json
  .vscode/tasks.json
  UIS.API/UIS.API/Controllers/UserController.cs
  UIS.API/UIS.DAL/Constants/MoodleAuthConstants.cs
  UIS.API/UIS.DAL/DTO/UserInfoDTO.cs
  src/index.js
Labels: enhancement

#46 discordID and guildID are crypted
  UIS.API/UIS.API/Controllers/UserController.cs
  package-lock.json
  package.json
  src/index.js
Labels: enhancement

#64 Added Generic repository and Student repository.
  UIS.API/UIS.DAL/Repository/GenericRepository.cs
  UIS.API/UIS.DAL/Repository/IGenericRepository.cs
  UIS.API/UIS.DAL/Repository/IStudentsRepository.cs
  UIS.API/UIS.DAL/Repository/StudentsRepository.cs
  UIS.API/UIS.DAL/UIS.DAL.csproj
Labels: enhancement

#66 56 user major and server
  UIS.API/UIS.API/Controllers/UserController.cs
  UIS.API/UIS.API/UIS.API.csproj
  src/index.js
Labels: enhancement

#68 Added Student repository.
  UIS.API/UIS.DAL/Repository/StudentsRepository.cs
Labels: enhancement

#69 Save student to DB service.
  UIS.API/UIS.API/Program.cs
  UIS.API/UIS.Services/Auth/AuthService.cs
  UIS.API/UIS.Services/Auth/IAuthService.cs
Labels: enhancement

#75 67 db check discord user
  .env
  .idea/.idea.UIS.dir/.idea/.gitignore
  .idea/.idea.UIS.dir/.idea/encodings.xml
  .idea/.idea.UIS.dir/.idea/indexLayout.xml
  .idea/.idea.UIS.dir/.idea/vcs.xml
  UIS.API/.idea/.idea.UIS.API/.idea/indexLayout.xml
  UIS.API/.idea/.idea.UIS.API/.idea/projectSettingsUpdater.xml
  UIS.API/.idea/.idea.UIS.API/.idea/shelf/Uncommitted_changes_before_rebase_[Changes]/shelved.patch
  UIS.API/.idea/.idea.UIS.API/.idea/shelf/Uncommitted_changes_before_rebase__Changes_.xml
  UIS.API/.idea/.idea.UIS.API/.idea/vcs.xml
  UIS.API/.idea/.idea.UIS.API/.idea/workspace.xml
  UIS.API/UIS.API/Controllers/UserController.cs
  src/index.js
Labels: enhancement

#82 Deleting migrations and merging them into one, due to problems.
  UIS.API/UIS.DATA/Migrations/20231207180519_InitialDbCreate.Designer.cs
  UIS.API/UIS.DATA/Migrations/20231212145614_AddGuildMajorTable.cs
  UIS.API/UIS.DATA/Migrations/20231217144921_ModifyStudentsTable.Designer.cs
  UIS.API/UIS.DATA/Migrations/20231217144921_ModifyStudentsTable.cs
  UIS.API/UIS.DATA/Migrations/20231217174535_InitialCreateDB.Designer.cs
  UIS.API/UIS.DATA/Migrations/20231217174535_InitialCreateDB.cs
Labels: enhancement

#83 79 sync command adn db intergration
  UIS.API/.idea/.idea.UIS.API/.idea/workspace.xml
  UIS.API/UIS.API/Controllers/UserController.cs
  UIS.API/UIS.Services/Auth/AuthService.cs
  src/index.js
Labels: enhancement

#84 35 refactor discordbot code
  src/database.js
  src/index.js
  src/registerCommands.js
  src/userfunctions.js
  src/utilites.js
Labels: enhancement

#88 Modified database.js file
  src/database.js
Labels: enhancement

#90 89 mocked data fix
  UIS.API/UIS.API/Controllers/UserController.cs
  src/database.js
  src/index.js
  src/userfunctions.js
  src/utilites.js
  uis.csv
Labels: bug, enhancement
